CONFIG:
  DEFAULT:
    EXECUTION_ENVIRONMENT: HML
    HEADLESS: False # True or False
  PROD:
    BASE_URL: https://www.saucedemo.com/
    BROWSER: firefox
    TIMEOUT:  15
  HML:
    BASE_URL: https://www.saucedemo.com/
    BROWSER: chrome
    TIMEOUT:  20
