name: Robot Framework

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
    Chrome:
        runs-on: ubuntu-latest
        continue-on-error: true

        steps:
        - name: Get Code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'

        - name: Setup Chrome
          uses: browser-actions/setup-chrome@v1
          with:
            chrome-version: stable

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            
        - name: Run tests
          run: |
            robot -d tests/results -v BROWSER:chrome tests
        
        - name: Robot Reporter
          uses: joonvena/robotframework-reporter-action@v2.4
          if: always()
          with:
            gh_access_token: ${{secrets.GITHUB_TOKEN}}
            report_path: tests/results
        
        - name: Upload Report
          uses: actions/upload-artifact@v4.3.3
          if: always()
          with:
            name: Chrome Report
            path: tests/results

    Firefox:
        runs-on: ubuntu-latest
        continue-on-error: true

        steps:
        - name: Get Code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'

        - name: Setup Firefox
          uses: browser-actions/setup-firefox@v1.5.1
          with:
            firefox-version: latest-esr

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            
        - name: Run tests
          run: |
            robot -d tests/results -v BROWSER:firefox tests
        
        - name: Robot Reporter
          uses: joonvena/robotframework-reporter-action@v2.4
          if: always()
          with:
            gh_access_token: ${{secrets.GITHUB_TOKEN}}
            report_path: tests/results
        
        - name: Upload Report
          uses: actions/upload-artifact@v4.3.3
          if: always()
          with:
            name: Firefox Report
            path: tests/results